version: '3'

services:
  fastapi:
    build:
      context: ./fastapi
    container_name: hiddenblueprint-backend
    command: uvicorn --reload main:app --host 0.0.0.0 --port 8010
    ports:
      - "8010:8010"
    volumes:
      - ./fastapi:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: hiddenblueprint-frontend

    ports:
      - "3010:3010"
    environment:
      - REACT_APP_USER_SERVICE_API_HOST=https://hbapi.leeseaver.com
      - NODE_ENV=development
      - HOST_OS=linux

    volumes:
      - ./frontend/src:/app/src    # Mount source code directory
      - ./frontend/public:/app/public  # Mount public directory
      - /app/node_modules           # Make sure node_modules is excluded from being mounted
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
